### ISSUE TITLE
I didn't make the catppuccin plymouth theme

### ISSUE THREAD

**Issue by isabelroses** [0fie/Maika#2]
I don't want to mislead anyone into thinking I did something that I didn't do. So I think its best to point out that your [README](https://github.com/0fie/Dotfiles/blob/d04a4b0e8d6469774a5e8b5b09a290a9b47fe3a0/README.md?plain=1#L133) incorrectly credits me for the plymouth theme.

**Comment by 0fie** [comment]
My bad. I might have misunderstood something. I took some code from your dotfiles though, i just cant seem to rember it.

Anyways, thanks! Will update the README.
